version: '2'
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      #- /srv/nginx/certs:/etc/nginx/certs:ro
      - ./volumes/certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - proxy-tier

  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    command: "-notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"
    volumes_from: [nginx]
    volumes:
      #- /srv/nginx/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - "./data/templates:/etc/docker-gen/templates:ro"
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    depends_on: [nginx-gen]
    volumes_from: [nginx]
    volumes:
      #- /srv/nginx/certs:/etc/nginx/certs:rw
      - ./volumes/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
    restart: always

networks:
  proxy-tier:
    external:
      name: nginx-proxy
